
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Jul 31 04:42:01 PDT 2013
//----------------------------------------------------

package org.sosy_lab.cpachecker.util.predicates.smtInterpol;

/** CUP generated interface containing symbol constants. */
public interface LexerSymbols {
  /* terminals */
  public static final int DECLAREFUN = 3;
  public static final int NAMED = 7;
  public static final int DECIMAL = 11;
  public static final int BINARY = 9;
  public static final int LPAR = 13;
  public static final int FORALL = 5;
  public static final int STRING = 12;
  public static final int EOF = 0;
  public static final int EXISTS = 4;
  public static final int NUMERAL = 10;
  public static final int error = 1;
  public static final int BANG = 2;
  public static final int RPAR = 14;
  public static final int LET = 6;
  public static final int HEXADECIMAL = 8;
}

