/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_yk_msvchecker_jni_checkJni */

#ifndef _Included_com_yk_msvchecker_jni_checkJni
#define _Included_com_yk_msvchecker_jni_checkJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_yk_msvchecker_jni_checkJni
 * Method:    dll_main
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_yk_msvchecker_jni_checkJni_dll_1main
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
